language: node_js
node_js: node
script: cd client && npm install && npm run test
deploy:
  provider: heroku
  app: rocky-atoll-79566
  api_key:
    secure: VPWAdPajTE4E/TMdjTPvHsL+W3Y2CV4mM5/H6pwXIh4BZ+bdSY6zPm2xoVj4TmnDC5GKH4xTPsvIHAKUHBbOQaDddxtvqLCyqMMzgl5a5Yr3cjOpw+INf0UsNuSp8mQebPk6jeYeZC/P1Qrpqn3B40tpSoWe3rN6AsIJMj/VZK6ALdSDuzdt4CG5E0ha1fpqIa/s8690yqQZmSwMilBO5nL8UTwlXnWVdQAE24ZhZEXHYq4lPSNxS0UC57xhairexf+oNj4+H7OSPrHzdCYik6Awg1wg5+h5hR19qHpz8Td676gAA23tBs5QRekRb7mCFF76Se70tbNYoH8rYA74S/NDonSToKXDPMR30/B/7AtSfTIByvTbfXxScsf7AgdWGoAL68F8rWaKL/1W6v9n7bYKCO1DH0fUVBh0T1oAPXtqk/61nqVR7juRsT3vcJrBxc3PC40wrV6uBwUUre2jk4fwgIwEPseTBemz076ycVglT54RQPPVXbde4ukqBU+ij7j8b6739QP/5DNjBaHP/LlBPOW4PnvsDgANM3vo9w1tKbozDLY7j/cDiw3EgC6+XW3SuDaRvi5wreiP/yut9V9z1d1nEaEs8+8uoMcGWkiYgxFche+oSJBIyABKS9tVd7J5AXLQvOEb9yjH9+0aJUTdPhkqYXnKIkXiSlDpe1o=
